### ISSUE TITLE
Clicking fetch data twice clears out all data

### ISSUE THREAD

**Issue by rahul051280** [mrpbennett/signal_debugger#8]

**Comment by mrpbennett** [comment]
Button has been removed and data is now present upon a refresh of the browser. After removing the button that generates the data there is a now a new bug.

It's something with the tab swapping. When the tab is reset (changed) the arrays that store the data are reset to `0` - but when going to the original page it seems they're called again and filled with double the data.

**Comment by mrpbennett** [comment]
Closing this out for now as fix has been committed under [296821e](https://github.com/mrpbennett/signal_debugger/commit/296821e3879ec67134bf6a474dcc30501e72e610) this commit is still on branch `work-#8` and needs to be merged with `main`,

Waiting for testings and confirmation from @jlinpp 

Please reopen if needed or create a new issue
